//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tkUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tkUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with the ID {0} wasn&apos;t found..
        /// </summary>
        internal static string App_Exceptions_IDSearchNotFound {
            get {
                return ResourceManager.GetString("App_Exceptions_IDSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee can&apos;t exist since the ID ({0}) is equal or less than zero..
        /// </summary>
        internal static string App_Exceptions_NegativeIDSearchEmployee {
            get {
                return ResourceManager.GetString("App_Exceptions_NegativeIDSearchEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string App_Messages_Fault_Error {
            get {
                return ResourceManager.GetString("App_Messages_Fault_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los siguientes IDs no fueron encontrados: .
        /// </summary>
        internal static string App_Messages_Fault_FollowingIDsWerentFound {
            get {
                return ResourceManager.GetString("App_Messages_Fault_FollowingIDsWerentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string App_Messages_Fault_Warning {
            get {
                return ResourceManager.GetString("App_Messages_Fault_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timekeeping.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowIcon {
            get {
                object obj = ResourceManager.GetObject("ArrowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar25 {
            get {
                object obj = ResourceManager.GetObject("avatar25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        internal static string BirthDate_Combobox_Day {
            get {
                return ResourceManager.GetString("BirthDate_Combobox_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string BirthDate_Combobox_Month {
            get {
                return ResourceManager.GetString("BirthDate_Combobox_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string BirthDate_Combobox_Year {
            get {
                return ResourceManager.GetString("BirthDate_Combobox_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClipBoardIcon {
            get {
                object obj = ResourceManager.GetObject("ClipBoardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClipBoardSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("ClipBoardSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseAliasing {
            get {
                object obj = ResourceManager.GetObject("CloseAliasing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreditCardIcon {
            get {
                object obj = ResourceManager.GetObject("CreditCardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreditCardSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("CreditCardSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DashboardIcon {
            get {
                object obj = ResourceManager.GetObject("DashboardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DashboardSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("DashboardSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección e-mail es inválida.
        /// </summary>
        internal static string Employee_Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Employee_Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la dirección.
        /// </summary>
        internal static string Employee_Error_MissingAddress {
            get {
                return ResourceManager.GetString("Employee_Error_MissingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese dirección e-mail.
        /// </summary>
        internal static string Employee_Error_MissingEmail {
            get {
                return ResourceManager.GetString("Employee_Error_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el sueldo.
        /// </summary>
        internal static string Employee_Error_MissingPay {
            get {
                return ResourceManager.GetString("Employee_Error_MissingPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese número de teléfono.
        /// </summary>
        internal static string Employee_Error_MissingPhone {
            get {
                return ResourceManager.GetString("Employee_Error_MissingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sueldo solo puede contener números.
        /// </summary>
        internal static string Employee_Error_PayContainsNonDigits {
            get {
                return ResourceManager.GetString("Employee_Error_PayContainsNonDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sueldo es mayor que el máximo en la compañía.
        /// </summary>
        internal static string Employee_Error_PayIsAboveMaximumWage {
            get {
                return ResourceManager.GetString("Employee_Error_PayIsAboveMaximumWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sueldo es menor que el mínimo.
        /// </summary>
        internal static string Employee_Error_PayIsBelowMinimumWage {
            get {
                return ResourceManager.GetString("Employee_Error_PayIsBelowMinimumWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El teléfono solo puede contener números.
        /// </summary>
        internal static string Employee_Error_PhoneContainsNonDigits {
            get {
                return ResourceManager.GetString("Employee_Error_PhoneContainsNonDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Empleado.
        /// </summary>
        internal static string EmployeeWrapperViewModel_AddEmployee {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Sin Especificar).
        /// </summary>
        internal static string EmployeeWrapperViewModel_ComboboxValue_NotSpecified {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_ComboboxValue_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha es inválida.
        /// </summary>
        internal static string EmployeeWrapperViewModel_Error_InvalidBirthDate {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Error_InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la fecha de nacimiento.
        /// </summary>
        internal static string EmployeeWrapperViewModel_Error_MissingBirthDate {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Error_MissingBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El género del empleado debe seleccionarse.
        /// </summary>
        internal static string EmployeeWrapperViewModel_Error_MissingGenderType {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Error_MissingGenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de usuario debe seleccionarse.
        /// </summary>
        internal static string EmployeeWrapperViewModel_Error_MissingUserType {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Error_MissingUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de jornada debe seleccionarse.
        /// </summary>
        internal static string EmployeeWrapperViewModel_Error_MissingWorkTime {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Error_MissingWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede guardar un empleado inválido..
        /// </summary>
        internal static string EmployeeWrapperViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro pasado a DeleteCommand debe ser un integer..
        /// </summary>
        internal static string EmployeeWrapperViewModel_Exception_DeleteWrongParam {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Exception_DeleteWrongParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro pasado a EditCommand debe ser un integer..
        /// </summary>
        internal static string EmployeeWrapperViewModel_Exception_EditWrongParam {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Exception_EditWrongParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el usuario buscado por el ID: {0}..
        /// </summary>
        internal static string EmployeeWrapperViewModel_Exception_EmployeeIDNotFound {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Exception_EmployeeIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede buscar a un empleado con un integer menor o igual que cero..
        /// </summary>
        internal static string EmployeeWrapperViewModel_Exception_IDLessOrEqualThanZero {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Exception_IDLessOrEqualThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro pasado a ViewCommand debe ser un integer..
        /// </summary>
        internal static string EmployeeWrapperViewModel_Exception_ViewWrongParam {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_Exception_ViewWrongParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mujer.
        /// </summary>
        internal static string EmployeeWrapperViewModel_GenderTypeOptions_Female {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_GenderTypeOptions_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hombre.
        /// </summary>
        internal static string EmployeeWrapperViewModel_GenderTypeOptions_Male {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_GenderTypeOptions_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar un usuario siendo editado.
        /// </summary>
        internal static string EmployeeWrapperViewModel_ToolTip_DeleteButton_Disabled {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_ToolTip_DeleteButton_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string EmployeeWrapperViewModel_ToolTip_DeleteButton_Enabled {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_ToolTip_DeleteButton_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden editar dos empleados al mismo tiempo.
        /// </summary>
        internal static string EmployeeWrapperViewModel_ToolTip_EditButton_Disabled {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_ToolTip_EditButton_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string EmployeeWrapperViewModel_ToolTip_EditButton_Enabled {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_ToolTip_EditButton_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string EmployeeWrapperViewModel_UserTypeOptions_Administrator {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_UserTypeOptions_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollador.
        /// </summary>
        internal static string EmployeeWrapperViewModel_UserTypeOptions_Developer {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_UserTypeOptions_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        internal static string EmployeeWrapperViewModel_UserTypeOptions_StandardUser {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_UserTypeOptions_StandardUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Completo.
        /// </summary>
        internal static string EmployeeWrapperViewModel_WorkingTimeOptions_FullTime {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_WorkingTimeOptions_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Parcial.
        /// </summary>
        internal static string EmployeeWrapperViewModel_WorkingTimeOptions_PartTime {
            get {
                return ResourceManager.GetString("EmployeeWrapperViewModel_WorkingTimeOptions_PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeIcon {
            get {
                object obj = ResourceManager.GetObject("EyeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("EyeSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string ForgotPasswordViewModel_Color_Blank {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel_Color_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string ForgotPasswordViewModel_Color_Error {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel_Color_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string ForgotPasswordViewModel_Color_Success {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel_Color_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Un email conteniendo el restablecimiento de tu clave fue enviado!.
        /// </summary>
        internal static string ForgotPasswordViewModel_Message_RecoveredPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordViewModel_Message_RecoveredPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header_bg_bar {
            get {
                object obj = ResourceManager.GetObject("Header_bg_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HumanIcon {
            get {
                object obj = ResourceManager.GetObject("HumanIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HumanSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("HumanSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación.
        /// </summary>
        internal static string ListEmployeesViewModel_Confirmation_Self {
            get {
                return ResourceManager.GetString("ListEmployeesViewModel_Confirmation_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea eliminar los {0} empleados seleccionados?.
        /// </summary>
        internal static string ListEmployeesViewModel_Format_ConfirmationRange {
            get {
                return ResourceManager.GetString("ListEmployeesViewModel_Format_ConfirmationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el rango porque contiene un empleado que está siendo editado.
        /// </summary>
        internal static string ListEmployeesViewModel_Warning_InvalidRange {
            get {
                return ResourceManager.GetString("ListEmployeesViewModel_Warning_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string ListEmployeesViewModel_Warning_Self {
            get {
                return ResourceManager.GetString("ListEmployeesViewModel_Warning_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se reconoce el e-mail..
        /// </summary>
        internal static string LoginViewModel_Error_EmailWasntFound {
            get {
                return ResourceManager.GetString("LoginViewModel_Error_EmailWasntFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es incorrecta..
        /// </summary>
        internal static string LoginViewModel_Error_WrongPassword {
            get {
                return ResourceManager.GetString("LoginViewModel_Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo1 {
            get {
                object obj = ResourceManager.GetObject("Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagnifyingGlassIcon {
            get {
                object obj = ResourceManager.GetObject("MagnifyingGlassIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagnifyingGlassSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("MagnifyingGlassSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaximizeAliasing {
            get {
                object obj = ResourceManager.GetObject("MaximizeAliasing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MinimizeAliasing {
            get {
                object obj = ResourceManager.GetObject("MinimizeAliasing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NeueHaasGroteskRegular {
            get {
                object obj = ResourceManager.GetObject("NeueHaasGroteskRegular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PencilThickIcon {
            get {
                object obj = ResourceManager.GetObject("PencilThickIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PencilThickSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("PencilThickSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PersonalIDIcon {
            get {
                object obj = ResourceManager.GetObject("PersonalIDIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PersonalIDSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("PersonalIDSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña? - .
        /// </summary>
        internal static string Session_ForgotPasswordViewModel_WindowTitle {
            get {
                return ResourceManager.GetString("Session_ForgotPasswordViewModel_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión - .
        /// </summary>
        internal static string Session_LoginViewModel_WindowTitle {
            get {
                return ResourceManager.GetString("Session_LoginViewModel_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Administrador - .
        /// </summary>
        internal static string Session_RegisterViewModel_WindowTitle {
            get {
                return ResourceManager.GetString("Session_RegisterViewModel_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrashIcon {
            get {
                object obj = ResourceManager.GetObject("TrashIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrashSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("TrashSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WrenchIcon {
            get {
                object obj = ResourceManager.GetObject("WrenchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WrenchSelectedIcon {
            get {
                object obj = ResourceManager.GetObject("WrenchSelectedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
