//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tkUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mujer")]
        public string EmployeeWrapperViewModel_GenderTypeOption_Female {
            get {
                return ((string)(this["EmployeeWrapperViewModel_GenderTypeOption_Female"]));
            }
            set {
                this["EmployeeWrapperViewModel_GenderTypeOption_Female"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hombre")]
        public string EmployeeWrapperViewModel_GenderTypeOption_Male {
            get {
                return ((string)(this["EmployeeWrapperViewModel_GenderTypeOption_Male"]));
            }
            set {
                this["EmployeeWrapperViewModel_GenderTypeOption_Male"] = value;
            }
        }
    }
}
